### ISSUE TITLE
Support Application Default Credentials for GCS

### ISSUE THREAD

**Issue by jmesterh** [flarco/dbio#14]
Similar to https://github.com/slingdata-io/sling-cli/issues/74 we would like to use application default credentials with GCS storage. 

The [filesys package](https://github.com/flarco/dbio/blob/main/filesys/fs_google.go#L69) will return an error if a key file is not provided.

**Comment by flarco** [comment]
Done. See https://github.com/flarco/dbio/commit/a70785e9fec68fc0afebfc0973bda61fc05bff8a
